#! /usr/bin/bash

URL="https://coronavirus-tracker-api.herokuapp.com/all"
res=$(curl -sf "$URL")

if [ -z "$res" ]; then
    echo " impossible to fetch data. "
    return 1
fi

nb_confirmed=$(jq '.["latest"]["confirmed"]' <<< $res)
nb_death=$(jq '.["latest"]["deaths"]' <<< $res)
nb_recovered=$(jq '.["latest"]["recovered"]' <<< $res)

echo "  $nb_confirmed |  $nb_death | ♥ $nb_recovered "
