#!/bin/sh

## /* info /
os="$(grep PRETTY /etc/os-release | cut -c 13- | tr -d '"' | tr '[A-Z]' '[a-z]')"
model="$(cat /sys/devices/virtual/dmi/id/product_family | tr '[A-Z]' '[a-z]')"
wm="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
packages="$(pacman -Q | wc -l)"
memory="$(free -h | sed -n '2{p;q}' | awk '{print $3 "/" $2}' | tr -d 'i' | tr '[A-Z]' '[a-z]')"



cat <<EOF


                   os: ${os}
     \    /\       model: ${model}
      )  ( ')      wm: ${wm}
     (  /  )       pkgs: ${packages}
       (__)|       ram: ${memory} 
 		    
		   
EOF
echo
